#!/usr/bin/env bash

# Gets project root automatically 
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

############################
# DIRECTORIES
############################

RAW_DATA_DIR="$PROJECT_ROOT/raw_data"
ANALYSIS_DIR="$PROJECT_ROOT/analysis"
LOGS_DIR="$PROJECT_ROOT/logs"


READ1_ACC="SRR34987610"
READ2_ACC="SRR34987611"
READ3_ACC="SRR34987612"
READ4_ACC="SRR34987613"

READ1_R1="$RAW_DATA_DIR/$READ1_ACC"_1.fastq.gz
READ1_R2="$RAW_DATA_DIR/$READ1_ACC"_2.fastq.gz
READ2_R1="$RAW_DATA_DIR/$READ2_ACC"_1.fastq.gz
READ2_R2="$RAW_DATA_DIR/$READ2_ACC"_2.fastq.gz
READ3_R1="$RAW_DATA_DIR/$READ3_ACC"_1.fastq.gz
READ3_R2="$RAW_DATA_DIR/$READ3_ACC"_2.fastq.gz
READ4_R1="$RAW_DATA_DIR/$READ4_ACC"_1.fastq.gz
READ4_R2="$RAW_DATA_DIR/$READ4_ACC"_2.fastq.gz

THREADS="8"

FASTQC_RAW_DIR="$ANALYSIS_DIR/fastqc_raw"
FASTQC_TRIMMED_DIR="$ANALYSIS_DIR/fastqc_trimmed"
TRIMMED_DIR="$ANALYSIS_DIR/trimmed"

REF_DIR="$ANALYSIS_DIR/reference"

HISAT2_INDEX="$REF_DIR/grch38_genome.tar.gz"
HISAT2_INDEX_DIR="$REF_DIR/grch38/genome"
HISAT_ALIGN_DIR="$ANALYSIS_DIR/hisat_alignment"

READ1_R1_PAIRED="$TRIMMED_DIR/$READ1_ACC"_1_paired.fastq.gz
READ1_R2_PAIRED="$TRIMMED_DIR/$READ1_ACC"_2_paired.fastq.gz
READ2_R1_PAIRED="$TRIMMED_DIR/$READ2_ACC"_1_paired.fastq.gz
READ2_R2_PAIRED="$TRIMMED_DIR/$READ2_ACC"_2_paired.fastq.gz
READ3_R1_PAIRED="$TRIMMED_DIR/$READ3_ACC"_1_paired.fastq.gz
READ3_R2_PAIRED="$TRIMMED_DIR/$READ3_ACC"_2_paired.fastq.gz
READ4_R1_PAIRED="$TRIMMED_DIR/$READ4_ACC"_1_paired.fastq.gz
READ4_R2_PAIRED="$TRIMMED_DIR/$READ4_ACC"_2_paired.fastq.gz

MULTIQC_DIR="$ANALYSIS_DIR/multiqc"

COUNT_DIR="$ANALYSIS_DIR/counts"

ANNOTATION_FILE="$COUNT_DIR/Homo_sapiens.GRCh38.115.gtf"